#!/usr/bin/env bash

if [[ -e ~/.bashrc ]]; then
    mv ~/.bashrc ~/.bashrc.bkp
fi

ln -s ~/.dotfiles/bashrc ~/.bashrc
ln -s ~/.dotfiles/gitconfig ~/.gitconfig
ln -s ~/.dotfiles/vim ~/.vim

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir -p ~/.local/share/vim/{backup,plugins,swap}
