#!/usr/bin/env bash

ln -s ~/.dotfiles/gitconfig ~/.gitconfig

ln -s ~/.dotfiles/vim ~/.vim
mkdir ~/.vim/{bkp,tmp,bundle}
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
wait
vim +PluginInstall +qall

if [[ -e ~/.bashrc ]]; then
    mv ~/.bashrc ~/.bashrc.bkp
fi

ln -s ~/.dotfiles/bashrc ~/.bashrc
