set nocompatible

call plug#begin('~/.local/share/vim/plugins')
Plug 'rust-lang/rust.vim'
call plug#end()

syntax enable
set background=dark

set title
set hidden
set ruler
set cmdheight=2
set showcmd
set encoding=utf-8
set fileencoding=utf-8
set lazyredraw
set history=50
set backspace=indent,eol,start
set whichwrap+=<,>,h,l,[,]
set nowrap
set cursorline
highlight CursorLine cterm=bold ctermbg=233
set colorcolumn=100
highlight ColorColumn ctermbg=233
set scrolloff=3
set backup
set backupdir=~/.local/share/vim/backup
set directory=~/.local/share/vim/swap
set viminfo+=n~/.local/share/vim/viminfo

set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

set list
set listchars=tab:→\ ,trail:·,extends:»,precedes:«

set mouse=a
nnoremap <space> za
